# Generated by Django 3.2.7 on 2021-09-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20210926_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='exam rules,sitting rules', max_length=100)),
                ('instruction', models.TextField(max_length=600)),
            ],
        ),
    ]
