# Generated by Django 3.2.7 on 2021-10-12 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_generalinstruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 12, 8, 36, 833419, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='course',
            name='time_of_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 12, 8, 36, 833307, tzinfo=utc)),
        ),
    ]
