# Generated by Django 3.2.7 on 2021-10-21 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20211021_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 10, 32, 7, 500165, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_of_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 10, 32, 7, 500042, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='generalinstruction',
            name='instruction',
            field=models.TextField(max_length=3000),
        ),
    ]
