# Generated by Django 3.2.7 on 2021-10-25 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20211021_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='finish_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 25, 12, 43, 19, 755788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_of_start',
            field=models.TimeField(default=datetime.datetime(2021, 10, 25, 12, 43, 19, 755675, tzinfo=utc)),
        ),
    ]
