# Generated by Django 3.2.7 on 2021-11-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20211025_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time_of_start',
        ),
        migrations.AddField(
            model_name='course',
            name='time_in_munites',
            field=models.IntegerField(default=0),
        ),
    ]
