# Generated by Django 3.2.7 on 2021-09-24 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ksusta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_title', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ksusta.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ksusta.facultie')),
            ],
        ),
    ]
