# Generated by Django 3.2.7 on 2021-09-24 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ksusta', '0002_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(default='', max_length=20, null=True)),
                ('profile_picture', models.ImageField(default='pics', upload_to='profile_pics')),
                ('admission_number', models.CharField(max_length=10)),
                ('level', models.CharField(choices=[('matric', 'MATRIC'), ('ijmb', 'IJMB'), ('nd1', 'ND1'), ('ug1', 'UG1')], default='UG1', max_length=6)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ksusta.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ksusta.facultie')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ksusta.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
