# Generated by Django 3.2.7 on 2021-09-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
