# Generated by Django 3.2.7 on 2021-09-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='firstname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='lastname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
