# Generated by Django 3.2.7 on 2021-09-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_result_student'),
        ('student', '0002_remove_student_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
